### ISSUE TITLE
Missing changelog for 2.2.0

### ISSUE THREAD

**Issue by dstansby** [sunpy/streamtracer#153]
### Describe the bug

https://docs.sunpy.org/projects/streamtracer/en/stable/#changelog doesn't seem to have a changelog entry for 2.2.0 (or 2.1.0?) - should it have one here? It's where I went looking to see how my little package was being ~~torn apart~~ lovingly maintained

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by nabobalis** [comment]
Yeah, I am not sure we decided on the changelog mechanism.

Right now it is just the github release pages but we should at least update the index file for the time being.
