### ISSUE TITLE
StreamTracer.trace TypeError: trace() missing 1 required positional argument: 'grid'

### ISSUE THREAD

**Issue by aleksyprok** [sunpy/streamtracer#65]
First of all, thank you for writing this code and making it public.

Running this code:
```
import numpy as np
from streamtracer import *

nsteps = 10000
step_size = 0.1
tracer = StreamTracer(nsteps, step_size)

field = np.ones((10, 10, 10, 3))
grid_spacing = [1, 2, 1]
grid = VectorGrid(field, grid_spacing)

seeds = np.array([[0, 0, 0], [0, 0, 1]])
streamlines = StreamTracer.trace(seeds, grid)
```
Gives the following error:
```
Traceback (most recent call last):
  File "streamtracer_test.py", line 13, in <module>
    streamlines = StreamTracer.trace(seeds, grid)
TypeError: trace() missing 1 required positional argument: 'grid'
```
Do you know why this is and how to fix this? I tried to stick as closely to [the example code](https://streamtracer.readthedocs.io/en/stable/) as possible.

**Comment by dstansby** [comment]
Thanks for spotting this 😄  The fix is to replace the last line with `tracer.trace(seeds, grid)`. I'm currently updating the documentation to fix this, and should be done soon.

**Comment by aleksyprok** [comment]
Thank you very much. I've got it working now and it works great.
