### ISSUE TITLE
Non-uniform structured grids

### ISSUE THREAD

**Issue by ddasilva** [sunpy/streamtracer#92]
I have data on a simulation grid which is non-uniform, but still "structured". As in, it is based off cells and I can supply `x[i, j, k]`, `y[i, j, k]`, and `z[i, j, k]` for each cell center. The indices are ordered based on the spherical coordinates (phi, theta, radius). 

Are these types of grids supported by this package?  My apologies if this is spelled out elsewhere, I couldn't tell from the documentation.

**Comment by dstansby** [comment]
I'm afraid this isn't supported - a `VectorGrid` can only have a uniform spacing specified. I've updated the docs to note that streamtracer is for uniform grids. Thanks for asking, and sorry to disappoint 😃
